//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public Appointments()
        {
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int AppointmentID { get; set; }
        public int ClientID { get; set; }
        public int MasterServiceID { get; set; }
        public System.DateTime AppointmentTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> QueueNumber { get; set; }
        public int StatusID { get; set; }
        public string Notes { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual MasterServices MasterServices { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual AppointmentStatuses AppointmentStatuses { get; set; }
    }
}
