//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collections
    {
        public Collections()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int CollectionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ImagePath { get; set; }
    
        public virtual ICollection<Services> Services { get; set; }
    }
}
