//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterServices
    {
        public MasterServices()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int MasterServiceID { get; set; }
        public int MasterID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<decimal> CustomPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual Users Users { get; set; }
        public virtual Services Services { get; set; }
    }
}
