//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatieSalonEntities1 : DbContext
    {
        public MatieSalonEntities1()
            : base("name=MatieSalonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appointments> Appointments { get; set; }
        public DbSet<MasterServices> MasterServices { get; set; }
        public DbSet<QualificationRequests> QualificationRequests { get; set; }
        public DbSet<RequestStatuses> RequestStatuses { get; set; }
        public DbSet<Reviews> Reviews { get; set; }
        public DbSet<ReviewTargets> ReviewTargets { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<ServiceCategories> ServiceCategories { get; set; }
        public DbSet<ServiceHistory> ServiceHistory { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<AppointmentStatuses> AppointmentStatuses { get; set; }
        public DbSet<Collections> Collections { get; set; }
        public DbSet<Services> Services { get; set; }
    }
}
