//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewTargets
    {
        public ReviewTargets()
        {
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int TargetID { get; set; }
        public string TargetName { get; set; }
    
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
