//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ReviewID { get; set; }
        public int AppointmentID { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public int TargetID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Appointments Appointments { get; set; }
        public virtual ReviewTargets ReviewTargets { get; set; }
    }
}
