//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistory
    {
        public int HistoryID { get; set; }
        public int ServiceID { get; set; }
        public int ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeDescription { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Services Services { get; set; }
    }
}
