//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieSalon_Arina_Mazitova_422.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Appointments = new HashSet<Appointments>();
            this.MasterServices = new HashSet<MasterServices>();
            this.QualificationRequests = new HashSet<QualificationRequests>();
            this.ServiceHistory = new HashSet<ServiceHistory>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public int RoleID { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> QualificationLevel { get; set; }
        public string Bio { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<MasterServices> MasterServices { get; set; }
        public virtual ICollection<QualificationRequests> QualificationRequests { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<ServiceHistory> ServiceHistory { get; set; }
    }
}
